"""Removed forein key integrity on url model

Revision ID: 15cb2b7db678
Revises: 20a498c79ee5
Create Date: 2026-05-25 12:56:01.442282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15cb2b7db678'
down_revision: Union[str, Sequence[str], None] = '20a498c79ee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('urls_user_id_fkey'), 'urls', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('urls_user_id_fkey'), 'urls', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
